"""Regenerate demo fixture profiles for PROVIDER=fixture.

    python -m scripts.make_fixtures

Writes tests/fixtures/profiles/<slug>.json for a few *demo* slugs using the mock
generator, with a fixed timestamp for stable git diffs. Curated fixtures that the
test suite asserts on (e.g. ada-lovelace.json) are hand-authored and NOT touched
by this script.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from pathlib import Path

from app.providers.mock import MockProfileProvider
from app.urls import normalize_linkedin_url

DEMO_SLUGS = ["demo-engineer", "demo-manager", "demo-scientist"]
FIXED_TS = datetime(2024, 1, 1, tzinfo=timezone.utc)
OUT = Path("tests/fixtures/profiles")


async def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    provider = MockProfileProvider(latency_seconds=0.0)
    for slug in DEMO_SLUGS:
        url = normalize_linkedin_url(f"https://www.linkedin.com/in/{slug}")
        result = await provider.fetch(url)
        result = result.model_copy(
            update={
                "source": "fixture",
                "scraped_at": FIXED_TS,
                "warnings": ["Canned demo fixture generated by scripts/make_fixtures."],
            }
        )
        path = OUT / f"{slug}.json"
        path.write_text(result.model_dump_json(indent=2), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    asyncio.run(main())
