"""MockProfileProvider — deterministic synthetic profiles.

This is the default provider. It fabricates a plausible, *fully-shaped* profile
from a seed derived from the URL slug, so:

* the same URL always yields the same data (great for demos and screenshots),
* no network call is made and no LinkedIn account is required,
* every downstream layer (queue, cache, persistence, API) is exercised for real.

The data is clearly synthetic and every result carries a warning saying so.
"""

from __future__ import annotations

import asyncio
import hashlib
import random
from datetime import UTC, datetime

from app.schemas import (
    Certification,
    Education,
    Experience,
    Language,
    Profile,
    ProfileResult,
    ProviderHealth,
    Skill,
)
from app.urls import profile_slug

_FIRST = ["Jordan", "Priya", "Wei", "Sofia", "Amir", "Nina", "Diego", "Aisha", "Lucas", "Mei"]
_LAST = [
    "Okafor", "Sharma", "Nguyen", "Rossi", "Haddad",
    "Kowalski", "Silva", "Khan", "Andersen", "Chen",
]
_CITIES = [
    "San Francisco, California, United States",
    "London, England, United Kingdom",
    "Berlin, Germany",
    "Bengaluru, Karnataka, India",
    "Toronto, Ontario, Canada",
    "Singapore",
]
_COMPANIES = [
    "Northwind", "Acme Cloud", "Globex", "Initech",
    "Umbrella Labs", "Hooli", "Stark Systems",
]
_TITLES = [
    "Senior Software Engineer",
    "Staff Engineer",
    "Engineering Manager",
    "Backend Engineer",
    "Data Scientist",
    "Product Manager",
]
_SCHOOLS = ["MIT", "University of Oxford", "IIT Bombay", "ETH Zurich", "Stanford University"]
_DEGREES = ["B.Sc.", "M.Sc.", "B.Eng.", "MBA"]
_FIELDS = ["Computer Science", "Electrical Engineering", "Data Science", "Business Administration"]
_SKILLS = [
    "Python", "Distributed Systems", "PostgreSQL", "Kubernetes", "FastAPI",
    "System Design", "Machine Learning", "TypeScript", "AWS", "Docker",
]
_LANGS = [("English", "Native or bilingual"), ("Spanish", "Professional working"),
          ("German", "Elementary"), ("Hindi", "Full professional")]


def _seed(slug: str) -> int:
    return int(hashlib.sha256(slug.encode("utf-8")).hexdigest(), 16) % (2**32)


def _build_profile(slug: str) -> Profile:
    rng = random.Random(_seed(slug))
    first = rng.choice(_FIRST)
    last = rng.choice(_LAST)
    name = f"{first} {last}"
    title = rng.choice(_TITLES)
    company = rng.choice(_COMPANIES)

    n_exp = rng.randint(2, 3)
    experience: list[Experience] = []
    year = rng.randint(2016, 2019)
    for i in range(n_exp):
        current = i == 0
        experience.append(
            Experience(
                title=rng.choice(_TITLES),
                company=rng.choice(_COMPANIES),
                employment_type="Full-time",
                location=rng.choice(_CITIES),
                start_date=f"{year} ",
                end_date=None if current else f"{year + rng.randint(1, 3)}",
                is_current=current,
                description=f"Worked on {rng.choice(_SKILLS)} and {rng.choice(_SKILLS)}.",
            )
        )
        year += rng.randint(2, 4)

    education = [
        Education(
            school=rng.choice(_SCHOOLS),
            degree=rng.choice(_DEGREES),
            field_of_study=rng.choice(_FIELDS),
            start_date=str(rng.randint(2008, 2012)),
            end_date=str(rng.randint(2013, 2016)),
        )
    ]

    skills = [Skill(name=s, endorsement_count=rng.randint(0, 99))
              for s in rng.sample(_SKILLS, k=rng.randint(4, 7))]

    certifications = [
        Certification(
            name="Certified Kubernetes Administrator",
            issuer="The Linux Foundation",
            issue_date=f"{rng.randint(2019, 2023)}",
            credential_url="https://example.com/credential/abc123",
        )
    ] if rng.random() > 0.4 else []

    langs = rng.sample(_LANGS, k=rng.randint(1, 3))
    languages = [Language(name=n, proficiency=p) for n, p in langs]

    return Profile(
        name=name,
        headline=f"{title} at {company}",
        location=rng.choice(_CITIES),
        about=(
            f"{first} is a {title.lower()} focused on building reliable systems. "
            "This is synthetic demo data generated by the mock provider."
        ),
        profile_photo_url=f"https://picsum.photos/seed/{slug}-avatar/400",
        banner_photo_url=f"https://picsum.photos/seed/{slug}-banner/1200/300",
        experience=experience,
        education=education,
        skills=skills,
        certifications=certifications,
        languages=languages,
    )


class MockProfileProvider:
    name = "mock"

    def __init__(self, latency_seconds: float = 0.3) -> None:
        # A small delay so the queued -> running -> done lifecycle is observable.
        self._latency = latency_seconds

    async def fetch(self, url: str) -> ProfileResult:
        await asyncio.sleep(self._latency)
        slug = profile_slug(url)
        return ProfileResult(
            url=url,
            source=self.name,
            scraped_at=datetime.now(UTC),
            profile=_build_profile(slug),
            warnings=["Synthetic data from MockProfileProvider — not real LinkedIn data."],
        )

    async def healthcheck(self) -> ProviderHealth:
        return ProviderHealth(provider=self.name, ok=True, detail="synthetic data, always ready")
